name: Hoodoo Online
favicon: null
layout_spectrum: 0.06388
typography_spectrum: 0.51419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#000000'
    - '#a5a5a4'
    - '#01c600'
    - '#c41719'
  brandStrength: 0.8627390952315181
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
