name: Hoodoo Online
favicon: null
layout_spectrum: 0.75722
typography_spectrum: 1
title: Hoodoo Online - Magic Spells and Witchcraft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44986890-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#00ce00'
    - '#ec0d70'
    - '#d3dbde'
    - '#587ed3'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
